### PR TITLE
WIP - Migrate to CAF

### PR DESCRIPTION
**Pull request by cvium**
Trying to migrate to CAF. I'm really just opening this PR now for those interested and to let you all know I'm working on it (can't assign myself to the issue without write perm).

**Current status**: _Ready_.

- Playback works
- Changing stream works
- Queue is not implemented

### CODE REVIEW

**Comment by anthonylavado** [comment]
@joshuaboniface Can we get this up on `apps`?

Then we can make a secondary app for testing.

**Comment by cvium** [comment]
Found a bug:

```
helpers.js?t=1556656778100:4 Uncaught (in promise) Error: Url name cannot be empty
    at getUrl (helpers.js?t=1556656778100:4)
    at helpers.js?t=1556656778100:429
    at Array.forEach (<anonymous>)
    at createStreamInfo (helpers.js?t=1556656778100:428)
    at playMediaSource (maincontroller.js?t=1556656778100:859)
    at maincontroller.js?t=1556656778100:647
```

Looks like the delivery url is undefined, which causes the error.

**Comment by YouKnowBlom** [comment]
I can't for the life of me get `--playback-logo-image` to work without ending up behind the text.

**Comment by cvium** [comment]
> I can't for the life of me get `--playback-logo-image` to work without it ending up behind the text.
> 
> It doesn't seem to be affected by anything in `jellyfin.css` either so that's not the culprit

Yes, it drove me crazy

**Comment by YouKnowBlom** [comment]
> Yes, it drove me crazy

After some testing as well as looking at how poweramp does it I figured out that it only works if you apply it before playing something. This is because, if there's no value set for `--playback-logo-image` before playback it'll use the application name in its place as some sort of fallback.

I believe it's possible to implement a "dynamic logo" by initially setting it to a temp value and then change it on playback via the code.

**Comment by YouKnowBlom** [comment]
I'm having some issues getting HLS streams to play. I'm currently forcing the media to be transcoded to TS, h264, AAC (All [supported](https://developers.google.com/cast/docs/media) by the CAF player) by setting "Chromecast streaming quality" to a lower value in the web ui.


<details><summary>Chromecast log:</summary>
cast.player.api.ErrorCode.PLAYBACK/104 = MEDIA_SRC_NOT_SUPPORTED

[Error codes](https://developers.google.com/cast/docs/caf_receiver/error_codes)

```
[  3.437s] [cast.player.hls.Adaptation] process segment 
[  3.449s] [cast.player.hls.Adaptation] start: 10.083422222222222 
[  3.451s] [cast.player.core.SegmentManager] 0: segment processed 
[  3.461s] [cast.player.core.SourceBufferManager] 0: abort 
[  3.464s] [cast.player.core.SourceBufferManager] 0: timestampOffset = -10.083422222222222 
[  3.466s] [cast.player.core.SourceBufferManager] 0: successfully append 64484 bytes 
[  3.470s] [cast.player.cea608.InbandCaptionsManager] Pending 1 
[  3.484s] [cast.player.core.SegmentManager] 0: send request to get segment. 

(WARNING) Mixed Content: The page at 'https://$CHROMECAST_RECEIVER_APP/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://$JFSERVERIP:8096/videos/cfe02182-4ca8-70eb-68d6-48b7aa85d6a5/hls1/main/1.ts?DeviceId=QW5kcmVhcyBDQzI=&MediaSourceId=cfe021824ca870eb68d648b7aa85d6a5&VideoCodec=h264&AudioCodec=mp3,aac,opus&AudioStreamIndex=1&VideoBitrate=64000&AudioBitrate=128000&PlaySessionId=80b9a952a46f43d6a97a7b3b1b6e885e&api_key=$API_KEY&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=e94abf6271e0185bca4dd0b6cf40d1fb&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=42&aac-audiochannels=2&TranscodeReasons=ContainerBitrateExceedsLimit'. This content should also be served over HTTPS.

Uncaught DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
    at Vh.Vj (https://www.gstatic.com/cast/sdk/libs/mediaplayer/1.0.0/media_player.js:167:321)
    at Ic (https://www.gstatic.com/cast/sdk/libs/mediaplayer/1.0.0/media_player.js:33:300)
    at SourceBuffer.Fc (https://www.gstatic.com/cast/sdk/libs/mediaplayer/1.0.0/media_player.js:34:368)
    at SourceBuffer.Dc.b (https://www.gstatic.com/cast/sdk/libs/mediaplayer/1.0.0/media_player.js:31:245)
[  3.572s] [cast.player.api.Player] error 
[  3.576s] [cast.player.api.Host] error: cast.player.api.ErrorCode.PLAYBACK/104
[  4.256s] [cast.framework.media.Player] player event: error 
[  4.258s] [cast.receiver.MediaManager] Load metadata error: [object Object] 
```
</details>

<details><summary>Server log:</summary>

```
[2020-03-03 16:31:34.625 +01:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 192000, MaxStaticBitrate: 192000, MusicStreamingTranscodingBitrate: 192000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "mp4,m4v", AudioCodec: "aac,mp3,opus,flac,vorbis", VideoCodec: "h264,vp8", Type: Video }, DirectPlayProfile { Container: "mkv", AudioCodec: "aac,mp3,opus,flac,vorbis", VideoCodec: "h264,vp8", Type: Video }, DirectPlayProfile { Container: "mov", AudioCodec: "aac,mp3,opus,flac,vorbis", VideoCodec: "h264", Type: Video }, DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: "mp3", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma,webm", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "vorbis,opus", VideoCodec: "VP8", Type: Video }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264", AudioCodec: "mp3,aac,opus", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "webm", Type: Video, VideoCodec: "vpx", AudioCodec: "vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp4", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3,opus,flac,vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: AudioChannels, Value: "2", IsRequired: True }], ApplyConditions: [], Codec: "aac", Container: null }, CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: null, Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline", IsRequired: True }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "42", IsRequired: True }, ProfileCondition { Condition: LessThanEqual, Property: VideoBitrate, Value: "30000000", IsRequired: True }], ApplyConditions: [], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: LessThanEqual, Property: VideoBitrate, Value: "30000000", IsRequired: True }], ApplyConditions: [], Codec: null, Container: null }, CodecProfile { Type: Audio, Conditions: [ProfileCondition { Condition: LessThanEqual, Property: AudioSampleRate, Value: "96000", IsRequired: True }], ApplyConditions: [], Codec: "flac", Container: null }], ResponseProfiles: [ResponseProfile { Container: "m4v", AudioCodec: null, VideoCodec: null, Type: Video, OrgPn: null, MimeType: "video/mp4", Conditions: [] }], SubtitleProfiles: [SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }] }
[2020-03-03 16:31:34.806 +01:00] [INF] User policy for "blom". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2020-03-03 16:31:34.807 +01:00] [INF] Bitrate exceeds DirectPlay limit: media bitrate: 2729548, max bitrate: 192000
[2020-03-03 16:31:34.808 +01:00] [INF] Bitrate exceeds DirectStream limit: media bitrate: 2729548, max bitrate: 192000
[2020-03-03 16:31:34.809 +01:00] [INF] Profile: "Unknown Profile", Path: "Z:\tesfiles\Movies\Crocodile Dundee (1986)\Crocodile Dundee (1986).mp4", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2020-03-03 16:31:34.812 +01:00] [INF] Bitrate exceeds DirectPlay limit: media bitrate: 2729548, max bitrate: 192000
[2020-03-03 16:31:34.813 +01:00] [INF] Bitrate exceeds DirectStream limit: media bitrate: 2729548, max bitrate: 192000
[2020-03-03 16:31:34.814 +01:00] [INF] Profile: "Unknown Profile", Path: "Z:\tesfiles\Movies\Crocodile Dundee (1986)\Crocodile Dundee (1986).mp4", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2020-03-03 16:31:34.815 +01:00] [INF] Bitrate exceeds DirectPlay limit: media bitrate: 2729548, max bitrate: 192000
[2020-03-03 16:31:34.817 +01:00] [INF] Bitrate exceeds DirectStream limit: media bitrate: 2729548, max bitrate: 192000
[2020-03-03 16:31:34.818 +01:00] [INF] Profile: "Unknown Profile", Path: "Z:\tesfiles\Movies\Crocodile Dundee (1986)\Crocodile Dundee (1986).mp4", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2020-03-03 16:31:36.533 +01:00] [INF] Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2020-03-03 16:31:36.534 +01:00] [INF] C:\Program Files\ffmpeg\bin\ffmpeg.exe -f mov,mp4,m4a,3gp,3g2,mj2 -i file:"Z:\tesfiles\Movies\Crocodile Dundee (1986)\Crocodile Dundee (1986).mp4" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 64000 -bufsize 128000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none  -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -vf "scale=trunc(min(max(iw\,ih*dar)\,426)/2)*2:trunc(ow/dar/2)*2" -copyts -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 128000  -f hls -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "C:\Users\Blom\AppData\Local\jellyfin\transcodes\ceeeb393225c89b2dccfcebbb1a8876f%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "C:\Users\Blom\AppData\Local\jellyfin\transcodes\ceeeb393225c89b2dccfcebbb1a8876f.m3u8"
[2020-03-03 16:31:37.051 +01:00] [WRN] HTTP Response 200 to "$JFSERVERIP". Time (slow): 0:00:00.5190284. "http://$JFSERVERIP:8096/videos/cfe02182-4ca8-70eb-68d6-48b7aa85d6a5/hls1/main/0.ts?DeviceId=QW5kcmVhcyBDQzI%3D&MediaSourceId=cfe021824ca870eb68d648b7aa85d6a5&VideoCodec=h264&AudioCodec=mp3,aac,opus&AudioStreamIndex=1&VideoBitrate=64000&AudioBitrate=128000&PlaySessionId=ba2765baba1f460788f80c3acebc6dd3&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=e94abf6271e0185bca4dd0b6cf40d1fb&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=42&aac-audiochannels=2&TranscodeReasons=ContainerBitrateExceedsLimit"
```
</details>

<details><summary>Browserdeviceprofile:</summary>

```JSON
{
    "DeviceProfile":{
        "MaxStreamingBitrate":192000,
        "MaxStaticBitrate":192000,
        "MusicStreamingTranscodingBitrate":192000,
        "DirectPlayProfiles":[
            {
                "Container":"mp4,m4v",
                "Type":"Video",
                "VideoCodec":"h264,vp8",
                "AudioCodec":"aac,mp3,opus,flac,vorbis"
            },
            {
                "Container":"mkv",
                "Type":"Video",
                "VideoCodec":"h264,vp8",
                "AudioCodec":"aac,mp3,opus,flac,vorbis"
            },
            {
                "Container":"mov",
                "Type":"Video",
                "VideoCodec":"h264",
                "AudioCodec":"aac,mp3,opus,flac,vorbis"
            },
            {
                "Container":"opus",
                "Type":"Audio"
            },
            {
                "Container":"mp3",
                "Type":"Audio",
                "AudioCodec":"mp3"
            },
            {
                "Container":"aac",
                "Type":"Audio"
            },
            {
                "Container":"m4a",
                "AudioCodec":"aac",
                "Type":"Audio"
            },
            {
                "Container":"flac",
                "Type":"Audio"
            },
            {
                "Container":"webma,webm",
                "Type":"Audio"
            },
            {
                "Container":"wav",
                "Type":"Audio"
            },
            {
                "Container":"webm",
                "Type":"Video",
                "AudioCodec":"vorbis,opus",
                "VideoCodec":"VP8"
            },
            {
                "Container":"flac",
                "Type":"Audio"
            }
        ],
        "TranscodingProfiles":[
            {
                "Container":"ts",
                "Type":"Audio",
                "AudioCodec":"aac",
                "Context":"Streaming",
                "Protocol":"hls",
                "MaxAudioChannels":"2",
                "MinSegments":"1",
                "BreakOnNonKeyFrames":true
            },
            {
                "Container":"aac",
                "Type":"Audio",
                "AudioCodec":"aac",
                "Context":"Streaming",
                "Protocol":"http",
                "MaxAudioChannels":"2"
            },
            {
                "Container":"mp3",
                "Type":"Audio",
                "AudioCodec":"mp3",
                "Context":"Streaming",
                "Protocol":"http",
                "MaxAudioChannels":"2"
            },
            {
                "Container":"opus",
                "Type":"Audio",
                "AudioCodec":"opus",
                "Context":"Streaming",
                "Protocol":"http",
                "MaxAudioChannels":"2"
            },
            {
                "Container":"wav",
                "Type":"Audio",
                "AudioCodec":"wav",
                "Context":"Streaming",
                "Protocol":"http",
                "MaxAudioChannels":"2"
            },
            {
                "Container":"opus",
                "Type":"Audio",
                "AudioCodec":"opus",
                "Context":"Static",
                "Protocol":"http",
                "MaxAudioChannels":"2"
            },
            {
                "Container":"mp3",
                "Type":"Audio",
                "AudioCodec":"mp3",
                "Context":"Static",
                "Protocol":"http",
                "MaxAudioChannels":"2"
            },
            {
                "Container":"aac",
                "Type":"Audio",
                "AudioCodec":"aac",
                "Context":"Static",
                "Protocol":"http",
                "MaxAudioChannels":"2"
            },
            {
                "Container":"wav",
                "Type":"Audio",
                "AudioCodec":"wav",
                "Context":"Static",
                "Protocol":"http",
                "MaxAudioChannels":"2"
            },
            {
                "Container":"ts",
                "Type":"Video",
                "AudioCodec":"mp3,aac,opus",
                "VideoCodec":"h264",
                "Context":"Streaming",
                "Protocol":"hls",
                "MaxAudioChannels":"2",
                "MinSegments":"1",
                "BreakOnNonKeyFrames":true
            },
            {
                "Container":"webm",
                "Type":"Video",
                "AudioCodec":"vorbis",
                "VideoCodec":"vpx",
                "Context":"Streaming",
                "Protocol":"http",
                "MaxAudioChannels":"2"
            },
            {
                "Container":"mp4",
                "Type":"Video",
                "AudioCodec":"aac,mp3,opus,flac,vorbis",
                "VideoCodec":"h264",
                "Context":"Static",
                "Protocol":"http"
            }
        ],
        "ContainerProfiles":[

        ],
        "CodecProfiles":[
            {
                "Type":"VideoAudio",
                "Codec":"aac",
                "Conditions":[
                    {
                        "Condition":"Equals",
                        "Property":"IsSecondaryAudio",
                        "Value":"false",
                        "IsRequired":"false"
                    },
                    {
                        "Condition":"LessThanEqual",
                        "Property":"AudioChannels",
                        "Value":"2",
                        "IsRequired":true
                    }
                ]
            },
            {
                "Type":"VideoAudio",
                "Conditions":[
                    {
                        "Condition":"Equals",
                        "Property":"IsSecondaryAudio",
                        "Value":"false",
                        "IsRequired":"false"
                    }
                ]
            },
            {
                "Type":"Video",
                "Codec":"h264",
                "Conditions":[
                    {
                        "Condition":"NotEquals",
                        "Property":"IsAnamorphic",
                        "Value":"true",
                        "IsRequired":false
                    },
                    {
                        "Condition":"EqualsAny",
                        "Property":"VideoProfile",
                        "Value":"high|main|baseline|constrained baseline"
                    },
                    {
                        "Condition":"LessThanEqual",
                        "Property":"VideoLevel",
                        "Value":"42"
                    },
                    {
                        "Condition":"LessThanEqual",
                        "Property":"VideoBitrate",
                        "Value":"30000000",
                        "IsRequired":true
                    }
                ]
            },
            {
                "Type":"Video",
                "Conditions":[
                    {
                        "Condition":"LessThanEqual",
                        "Property":"VideoBitrate",
                        "Value":"30000000"
                    }
                ]
            },
            {
                "Type":"Audio",
                "Codec":"flac",
                "Conditions":[
                    {
                        "Condition":"LessThanEqual",
                        "Property":"AudioSampleRate",
                        "Value":"96000"
                    }
                ]
            }
        ],
        "SubtitleProfiles":[
            {
                "Format":"vtt",
                "Method":"External"
            }
        ],
        "ResponseProfiles":[
            {
                "Type":"Video",
                "Container":"m4v",
                "MimeType":"video/mp4"
            }
        ]
    }
}
```
</details>

<details><summary>PlaybackInfo:</summary>

```JSON
"MediaSources":[
        {
            "Protocol":"File",
            "Id":"cfe021824ca870eb68d648b7aa85d6a5",
            "Path":"Z:\\tesfiles\\Movies\\Crocodile Dundee (1986)\\Crocodile Dundee (1986).mp4",
            "Type":"Default",
            "Container":"mov",
            "Size":2000052532,
            "Name":"Crocodile Dundee (1986)",
            "IsRemote":false,
            "ETag":"e94abf6271e0185bca4dd0b6cf40d1fb",
            "RunTimeTicks":58619300000,
            "ReadAtNativeFramerate":false,
            "IgnoreDts":false,
            "IgnoreIndex":false,
            "GenPtsInput":false,
            "SupportsTranscoding":true,
            "SupportsDirectStream":false,
            "SupportsDirectPlay":false,
            "IsInfiniteStream":false,
            "RequiresOpening":false,
            "RequiresClosing":false,
            "RequiresLooping":false,
            "SupportsProbing":true,
            "VideoType":"VideoFile",
            "MediaStreams":[
                {
                    "Codec":"h264",
                    "CodecTag":"avc1",
                    "Language":"und",
                    "TimeBase":"1/11988",
                    "CodecTimeBase":"125/5994",
                    "VideoRange":"SDR",
                    "DisplayTitle":"1080P H264",
                    "NalLengthSize":"4",
                    "IsInterlaced":false,
                    "IsAVC":true,
                    "BitRate":2498640,
                    "BitDepth":8,
                    "RefFrames":1,
                    "IsDefault":true,
                    "IsForced":false,
                    "Height":816,
                    "Width":1920,
                    "AverageFrameRate":23.976,
                    "RealFrameRate":23.976,
                    "Profile":"High",
                    "Type":"Video",
                    "AspectRatio":"2.35:1",
                    "Index":0,
                    "IsExternal":false,
                    "IsTextSubtitleStream":false,
                    "SupportsExternalStream":false,
                    "PixelFormat":"yuv420p",
                    "Level":41
                },
                {
                    "Codec":"aac",
                    "CodecTag":"mp4a",
                    "Language":"eng",
                    "TimeBase":"1/48000",
                    "CodecTimeBase":"1/48000",
                    "DisplayTitle":"Eng AAC stereo Default",
                    "IsInterlaced":false,
                    "ChannelLayout":"stereo",
                    "BitRate":224000,
                    "Channels":2,
                    "SampleRate":48000,
                    "IsDefault":true,
                    "IsForced":false,
                    "Profile":"LC",
                    "Type":"Audio",
                    "Index":1,
                    "IsExternal":false,
                    "IsTextSubtitleStream":false,
                    "SupportsExternalStream":false,
                    "Level":0
                }
            ],
            "MediaAttachments":[

            ],
            "Formats":[

            ],
            "Bitrate":2729548,
            "RequiredHttpHeaders":{

            },
            "TranscodingUrl":"/videos/cfe02182-4ca8-70eb-68d6-48b7aa85d6a5/master.m3u8?DeviceId=QW5kcmVhcyBDQzI=&MediaSourceId=cfe021824ca870eb68d648b7aa85d6a5&VideoCodec=h264&AudioCodec=mp3,aac,opus&AudioStreamIndex=1&VideoBitrate=64000&AudioBitrate=128000&PlaySessionId=74013aa2ec2240c0875e2c9cec19410b&api_key=$API_KEY&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=e94abf6271e0185bca4dd0b6cf40d1fb&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=42&aac-audiochannels=2&TranscodeReasons=ContainerBitrateExceedsLimit",
            "TranscodingSubProtocol":"hls",
            "TranscodingContainer":"ts",
            "DefaultAudioStreamIndex":1
        }
    ]
```
</details>

<details><summary>master.m3u8:</summary>

```
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=192000,AVERAGE-BANDWIDTH=192000
main.m3u8?DeviceId=QW5kcmVhcyBDQzI=&MediaSourceId=cfe021824ca870eb68d648b7aa85d6a5&VideoCodec=h264&AudioCodec=mp3,aac,opus&AudioStreamIndex=1&VideoBitrate=64000&AudioBitrate=128000&PlaySessionId=74013aa2ec2240c0875e2c9cec19410b&api_key=$API_KEY&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=e94abf6271e0185bca4dd0b6cf40d1fb&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=42&aac-audiochannels=2&TranscodeReasons=ContainerBitrateExceedsLimit

```
</details>

<details><summary>main.m3u8:</summary>

[main.txt](https://github.com/jellyfin/jellyfin-chromecast/files/4282194/main.txt)
</details>


I noticed something odd, it seems a caption track is added to the video element despite not having any external or embedded subtitles

<details><summary>Videoelement on playback:</summary>

```HTML
<video aria-hidden="true" class="mediaElement" id="castMediaElement" style="height:100%;width:100%" poster="" crossorigin="anonymous" src="blob:https://$CHROMECAST_RECEIVER_APP/47aa05c3-e3c8-46e1-beb6-886276b7154b">
    <track src="http://$JFSERVERIP:8096/videos/cfe02182-4ca8-70eb-68d6-48b7aa85d6a5/master.m3u8?DeviceId=QW5kcmVhcyBDQzI=&amp;MediaSourceId=cfe021824ca870eb68d648b7aa85d6a5&amp;VideoCodec=h264&amp;AudioCodec=mp3,aac,opus&amp;AudioStreamIndex=1&amp;VideoBitrate=64000&amp;AudioBitrate=128000&amp;PlaySessionId=5ef0b0f832cd47c1b1c1254299e5d8ce&amp;api_key=$API_KEY&amp;TranscodingMaxAudioChannels=2&amp;RequireAvc=false&amp;Tag=e94abf6271e0185bca4dd0b6cf40d1fb&amp;SegmentContainer=ts&amp;MinSegments=1&amp;BreakOnNonKeyFrames=True&amp;h264-profile=high,main,baseline,constrainedbaseline&amp;h264-level=42&amp;aac-audiochannels=2&amp;TranscodeReasons=ContainerBitrateExceedsLimit#t=345" kind="captions">
</video>

```
</details>

**Comment by YouKnowBlom** [comment]
I managed to figure it out. I compared the example HLS streams that apple provides with the one jellyfin generates and noticed that the `CODECS` field was missing, after that I tried hardcoding a `CODECS` field with AAC-LE in the master playlist and got music streaming to work. https://github.com/jellyfin/jellyfin/issues/2505


In my opinion this PR cannot be merged before this issue is fixed.

**Comment by dkanada** [comment]
@YouKnowBlom before you add anything else, we might want to review and merge this pull request so you can start submitting changes on the main repository.

**Comment by YouKnowBlom** [comment]
@dkanada those should be the last commits on this pr, fingers crossed🤞. Just wanted to bump the version and fix the merge conflict. The status can now be changed to "Ready" :)

**Pull request merged**
