### PR TITLE
Add css linting and lint workflow to github action

### PR DESCRIPTION
**Pull request by YouKnowBlom**
Add css linting via stylelint and fix issues in `jellyfin.css`.
Remove `glyphicons.css` as it's unused.
Add lint step to github actions.
Remove lint step from Azure CI

### CODE REVIEW

**Comment by YouKnowBlom** [comment]
Seems the prettier worked its magic on the azure ci file

**Comment by simonmarklar** [comment]
@YouKnowBlom you can turn off whitespace changes in the review to ignore the prettier changes

should the `src/fonts/glyphicons-*` files be removed as well ?

**Review by nielsvanvelzen — APPROVED** [review]
Workflow file looks good 👍

**Comment by YouKnowBlom** [comment]
> should the `src/fonts/glyphicons-*` files be removed as well ?

Ah I missed those, good point :+1:

**Pull request merged**
