### PR TITLE
refactor changeStream nested promise chain

### PR DESCRIPTION
**Pull request by alexmaras**
Refactored the `changeStream` function to clean up a nested promise chain and make it more readable.
No logic changes have occurred here - the internal function has been made `async` in order to handle the promises in a more linear fashion and avoid the `new Promise`/`resolve()` pattern and still maintain order of operations

### CODE REVIEW

**Comment by YouKnowBlom** [comment]
Awesome! If it is one thing this client needs it's definitely refactoring. Will take a look ASAP.

**Comment by alexmaras** [comment]
Great, thanks! I noticed https://github.com/jellyfin/jellyfin-chromecast/pull/59 working towards some similar improvements - I'd be happy to help out with an effort to convert to some of those newer constructs (`async`/`await`, `const` etc)

Is there documentation on how best to test this codebase locally?

**Comment by YouKnowBlom** [comment]
> I'd be happy to help out with an effort to convert to some of those newer constructs (async/await, const etc)

Please do, that would be very much appreciated! :)

> Is there documentation on how best to test this codebase locally?

There isn't currently a good way to test without a cast device unfortunately. I've looked into it a little bit and there seems to be ways to emulate a device with [this](https://github.com/ajhsu/chromecast-device-emulator) and test that way, but I haven't had the time to look into it further.

**Comment by SteveDinn** [comment]
I'd like to help test this as well. I'm anxious to have a better chrommecast client, but I'm not sure how (or where) to apply any updates.

**Comment by neopc10** [comment]
> I'd like to help test this as well. I'm anxious to have a better chrommecast client, but I'm not sure how (or where) to apply any updates.

I think maincontroller.js is in need of [Queueing ](https://developers.google.com/cast/docs/web_receiver/core_features)support for the web receiver and then [Cast Connect](https://developers.google.com/cast/docs/android_tv_receiver) receiver support for the Android TV repo in preparation for the new devices due out.

The Android 2.0.0 repo is in need of a new [Android sender](https://developers.google.com/cast/docs/android_sender/intent_to_join), as I believe it is currently missing.  If jellyfin-web's Google Cast ever gets separated away, I'm sure the Chrome sender would benefit from a one-over.

**Review by YouKnowBlom — APPROVED** [review]
Sorry for the delay, #60 blocked me when I got the time to test. Works perfectly from my testing, thanks for the PR :)

**Pull request merged**
