### PR TITLE
Migrate from file-loader webpack asset modules

### PR DESCRIPTION
**Pull request by rhysmdnz**
This fixes images such as the jellyfin logo failing to load

### CODE REVIEW

**Comment by printfn** [comment]
Is there anything blocking this from getting merged?

**Review by nielsvanvelzen — CHANGES_REQUESTED** [review]
I think you can `npm rm file-loader` now.

**Comment by rhysmdnz** [comment]
It seems so. Removed :)

**Review by nielsvanvelzen — APPROVED** [review]

**Comment by nielsvanvelzen** [comment]
Thanks for the wait - as you might have noticed the development on the cast client stalled so I can't say anything on when this would be published with a new version. I believe the master branch is deployed to the unstable instance though.

**Pull request merged**
