### PR TITLE
Bump package versions

### PR DESCRIPTION
**Pull request by IDisposable**
Fixes npm security warning
typescript-eslint 8.9.0 -> 8.10.0
vite 5.4.8 -> 5.4.9
vitest 2.1.2 -> 2.1.3

### CODE REVIEW

**Comment by thornbill** [comment]
We use renovate for automating dependency updates

**Comment by IDisposable** [comment]
I was just trying to get caught up before adding some actual PRs. Close if you want.

**Comment by nielsvanvelzen** [comment]
You can see all pending dependency updates in the "Dependency Dashboard" issue: #415. It is automatically updated. Whenever a dependency update is released the bot will wait 3 days before opening the pull request. I merged all those updates a day ago so everything is nearly updated to latest.

**Comment by thornbill** [comment]
We did bump npm to 7 days due to how volatile that ecosystem can be.

**Pull request closed without merging**
